version: "3"

services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
    - 6379:6379

  registry:
    build: eureka
    restart: always
    depends_on:
      - redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
    - 8761:8761

  gateway:
    build: gateway
    restart: always
    depends_on:
      - registry
    environment:
      REGISTRY_HOST: registry
      REDIS_HOST: redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
    - 8080:8080

  admin:
    build: admin
    restart: always
    depends_on:
      - registry
    environment:
      REGISTRY_HOST: registry
      REDIS_HOST: redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8090:8090

  room:
    build: room
    restart: always
    depends_on:
      - registry
    environment:
      REGISTRY_HOST: registry
      REDIS_HOST: redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8100:8100

  room2:
    build: room
    restart: always
    depends_on:
      - registry
    environment:
      REGISTRY_HOST: registry
      REDIS_HOST: redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

