server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      discovery:
        locator:
          enabled: true # 启用服务发现
          lower-case-service-id: true
      routes:
        - id: admin-center
          uri: lb://admin-service
          predicates:
            - Path=/admin/**

        - id: room-admin-center
          uri: no://op
          predicates:
            - Path=/room/admin/**
          filters:
            - SetStatus=404

        - id: room-center
          uri: lb://room-service
          predicates:
            - Path=/room/**

eureka:
  client:
    service-url:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka/